name: 'native4kids '
favicon: null
layout_spectrum: 0.39561816258355975
typography_spectrum: 0.191520658088848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.628480413928628
  lightness: 0.2502362609375268
  saturation: 0.6075918928254396
  rhythmicContrast: 0.5567554559092969
purpose: []
